CFLAGS != pkg-config --cflags sdl gl glu
CFLAGS += -I/usr/local/include
LDFLAGS != pkg-config --libs sdl gl glu
CC = cc

all: test1 test2

clean:
	rm -f *.o sdlgl test1 test2

sdlgl: sdlgl.o
	$(CC) -o $@ $> $(LDFLAGS)

test1: test1.o
	$(CC) -o $@ $> $(LDFLAGS)

test2: test2.o
	$(CC) -o $@ $> $(LDFLAGS)
